### ISSUE TITLE
hudson plugs regression  (ros ticket #4547)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_plugs#57]
reproduce by:
{{{
roscd pr2_plugs_gazebo_demo
rosmake
make test
}}}

changes:
{{{
http://build.willowgarage.com/view/gazebo/job/gazebo-cturtle-plugging-in/2340/changes
}}}

log file:
{{{
http://build.willowgarage.com/view/gazebo/job/gazebo-cturtle-plugging-in/2340/consoleText
}}}

relevant snippet:
{{{
  [0m[ INFO] [199.770000000]: /vision_plug_detection: Received new goal[0m
  [0m[ INFO] [200.853000000]: /vision_plug_detection: Received image, performing detection[0m
  entered filterfeaturesonedges
  [0m[ INFO] [208.086000000]: /vision_plug_detection: Received new go[ERROR] 1278734840.802431: Exception in your execute callback: You requested a transform that is 1278734631632.090 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734631642.090 miliseconds old.

  Traceback (most recent call last):
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/common/actionlib/src/actionlib/simple_action_server.py", line 326, in executeLoop
      self.execute_callback(goal)
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/pr2_plugs/pr2_plugs_actions/scripts/detect_plug_on_base.py", line 65, in execute_cb
      transformer.waitForTransform("base_link", pose_detect_plug.header.frame_id, pose_detect_plug.header.stamp, rospy.Duration(2.0))
  Exception: You requested a transform that is 1278734631632.090 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734631642.090 miliseconds old.

  [ERROR] 1278734895.736587: Exception in your execute callback: You requested a transform that is 1278734678366.218 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734678376.218 miliseconds old.

  Traceback (most recent call last):
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/common/actionlib/src/actionlib/simple_action_server.py", line 326, in executeLoop
      self.execute_callback(goal)
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/pr2_plugs/pr2_plugs_actions/scripts/detect_plug_on_base.py", line 65, in execute_cb
      transformer.waitForTransform("base_link", pose_detect_plug.header.frame_id, pose_detect_plug.header.stamp, rospy.Duration(2.0))
  Exception: You requested a transform that is 1278734678366.218 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734678376.218 miliseconds old.

  [ERROR] 1278734950.543322: Exception in your execute callback: You requested a transform that is 1278734724972.941 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734724992.941 miliseconds old.

  Traceback (most recent call last):
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/common/actionlib/src/actionlib/simple_action_server.py", line 326, in executeLoop
      self.execute_callback(goal)
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/pr2_plugs/pr2_plugs_actions/scripts/detect_plug_on_base.py", line 65, in execute_cb
      transformer.waitForTransform("base_link", pose_detect_plug.header.frame_id, pose_detect_plug.header.stamp, rospy.Duration(2.0))
  Exception: You requested a transform that is 1278734724972.941 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734724992.941 miliseconds old.

   result ABORTED.
  [INFO] 1278734505.399490: State machine transitioning 'DETECT_PLUG_ON_BASE':'aborted'-->'MOVE_ARM_BASE_DETECT_POSE'
  [INFO] 1278734536.936798: Action r_arm_controller/joint_trajectory_generator terminated after 4.821 seconds with result SUCCEEDED.
}}}
{{{
  [INFO] 1278734950.545905: Action detect_plug_on_base terminated after 3.376 seconds with result ABORTED.[ERROR] 1278735032.238174: Could not execute goal callback: Traceback (most recent call last):
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/executive_python/smach/src/smach/simple_action_state.py", line 259, in enter
      goal_update = self._goal_cb(self.userdata, self._goal)
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/pr2_plugs/pr2_plugs_actions/scripts/fetch_plug.py", line 101, in get_approach_plug_goal
      pose_gripper_wrist = PoseStampedMath().fromTf(TFUtil.wait_and_lookup('r_gripper_tool_frame', 'r_wrist_roll_link'))
    File "/home/wgsim/hudson/workspace/gazebo-cturtle-plugging-in/ros-pkg/executive_python/executive_python_common/src/executive_python_common/tf_util.py", line 44, in wait_and_lookup
      TFUtil.listener.waitForTransform(parent_frame_id, child_frame_id, time, rospy.Duration(2.0))
  Exception: You requested a transform that is 1278734794650.917 miliseconds in the past, 
  but the most recent transform in the tf buffer is 1278734794667.917 miliseconds old.
}}}
}}}

trac data:
- Owner: **wim**
- Reporter: **hsu**
- Reported at: **Sat Jul 10 11:54:52 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4547

**Comment by ahendrix** [comment]
[wim] This seems to be another problem with time and ros. Even though "use_sim_time" is set, some nodes are using wall time.  Possible causes:
- The python tf library, as this part of the code needed a bunch of ugly hacks to get it to work with the new ros time api. 
- Something in roscpp, as the timestamps of the log messages are a mix of sim and wall time.

**Comment by ahendrix** [comment]
[hsu] [http://build.willowgarage.com/view/gazebo/job/gazebo-cturtle-plugging-in/2340/ test fails with geometry-1.1.8,][http://build.willowgarage.com/view/gazebo/job/gazebo-cturtle-plugging-in/2356/ temporary fix by switching to geometry-1.1.7.]

**Comment by ahendrix** [comment]
[wim] So the problem is in tf waitForTransform, which uses ros::ok(). But since this code gets wrapped in PyTF, the ros::ok() always returns false. I'll release geometry 1.1.9 after the buildtest succeeds.
